### ISSUE TITLE
Aluno precisa preencher projeto de TCC

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#10]
Verificar como está essa feature.

**Comment by lucaslarcher** [comment]
1) Em primeiro Lugar eu adicionei um boolean a tabela TCC para dizer se aquele trabalho é ou não um projeto

2) Feito isso é preciso mudar o model do TCC

+ A Variavel
/**
	 * Campo com a situação do tcc (projeto ou não). Relaciona com a coluna
	 * {@code projeto} do banco através da anotação
	 * {@code @Column(name = "projeto", nullable = false)}.
	 */
	@Column(name = "projeto", nullable = false)
	private boolean projeto;

+ seus gets e sets:

	public boolean isProjeto() {
		return projeto;
	}

	public void setProjeto(boolean projeto) {
		this.projeto = projeto;
	}

3) Com isso pronto, eu preciso remover os projetos das buscas de TCCs, então eu preciso procurar no BD apenas os que não são projetos.

para isso eu adicionei uma nova exigência na busca nos casos que eu julguei necessário e tambem as mudanças necessárias no TCCBussines, lembrando que chamamos o Bussines nessa para chamar o DAO.

"t.projeto = :projeto"
query.setParameter("projeto", false);

	public List<TCC> getTCCsNotConceptualized() {
		List<TCC> results = null;

		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador WHERE t.conceitoFinal = -1");
			results = query.list();
			getSession().close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return results;
	}

	public List<TCC> getAll() { //tccs
		List<TCC> results = null;

		try {
			Query query = getSession().createQuery("SELECT t FROM TCC AS t WHERE t.projeto = :projeto");
			query.setParameter("projeto", false);
			
			results = query.list();
			getSession().close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return results;
	}
	
	public List<TCC> getTCCsByCurso(Curso curso) {
		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador WHERE a.curso = :curso AND t.projeto = :projeto ORDER BY t.dataEnvioFinal DESC");
			query.setParameter("curso", curso);
			query.setParameter("projeto", false);

			List<TCC> resultados = query.list();

			getSession().close();

			if (resultados != null)
				return resultados;

		} catch (Exception e) {
			e.printStackTrace();
		}

		return null;
	}

	public List<TCC> getCurrentTCCByAuthor(Usuario user,
			CalendarioSemestre currentCalendar) {
		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH a.curso JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador LEFT JOIN FETCH t.participacoes AS p  LEFT JOIN FETCH p.professor WHERE t.aluno = :user AND t.calendarioSemestre = :currentCalendar");
			query.setParameter("user", user);
			query.setParameter("currentCalendar", currentCalendar);
			


			List<TCC> resultados = query.list();

			getSession().close();
			
			if (resultados != null)
				return resultados;

		} catch (Exception e) {
			e.printStackTrace();
		}

		return null;
	}
	
	public TCC getCurrentTCCByAuthor(Usuario user,
			CalendarioSemestre currentCalendar,boolean project) {
		TCC resultado = null;
		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH a.curso JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador LEFT JOIN FETCH t.participacoes AS p  LEFT JOIN FETCH p.professor WHERE t.aluno = :user AND t.calendarioSemestre = :currentCalendar AND t.projeto = :projeto");
			query.setParameter("user", user);
			query.setParameter("currentCalendar", currentCalendar);
			query.setParameter("projeto", project);

			resultado = (TCC) query.uniqueResult();

			getSession().close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return resultado;
	}
	
	
	
	public List<TCC> getTCCByCursoAndCalendar(Curso curso, CalendarioSemestre currentCalendar) {
		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH a.curso JOIN FETCH t.orientador WHERE a.curso = :curso AND t.calendarioSemestre = :currentCalendar");
			query.setParameter("curso", curso);
			query.setParameter("currentCalendar", currentCalendar);

			List<TCC> resultados = query.list();

			getSession().close();

			if (resultados != null)
				return resultados;

			getSession().close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return null;
	}

	public List<TCC> getTCCsByOrientador(Usuario user) {
		List<TCC> results = null;

		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador WHERE t.orientador = :user OR t.coOrientador = :user AND t.projeto = :projeto");
			query.setParameter("user", user);
			query.setParameter("projeto", false);
			results = query.list();
			getSession().close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return results;
	}

	public List<TCC> getTCCsByUserParticipacao(Usuario user) {
		List<TCC> results = null;

		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador LEFT JOIN t.participacoes AS p WHERE p.professor = :user AND t.projeto = :projeto");
			query.setParameter("user", user);
			query.setParameter("projeto", false);
			results = query.list();
			getSession().close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return results;
	}

	public boolean userHasTCC(Usuario user) {
		List<TCC> resultados = null;
		try {
			Query query = getSession().createQuery(
					"SELECT t FROM TCC AS t WHERE t.aluno = :user AND t.projeto = :projeto");
			query.setParameter("user", user);
			query.setParameter("projeto", false);

			resultados = query.list();

			getSession().close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return resultados.size() > 0;
	}

	public List<TCC> getFinishedTCCsByCurso(Curso curso) {
		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador WHERE a.curso = :curso AND t.dataEnvioFinal IS NOT NULL AND t.arquivoTCCFinal IS NOT NULL AND t.projeto = :projeto ORDER BY t.dataEnvioFinal DESC");
			query.setParameter("curso", curso);
			query.setParameter("projeto", false);

			List<TCC> resultados = query.list();

			getSession().close();

			if (resultados != null)
				return resultados;

		} catch (Exception e) {
			e.printStackTrace();
		}

		return null;
	}

	public List<TCC> getTCCsByAuthor(Usuario user) {
		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH a.curso JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador LEFT JOIN FETCH t.participacoes AS p  LEFT JOIN FETCH p.professor WHERE t.aluno = :user ORDER BY t.dataEnvioBanca DESC");
			query.setParameter("user", user);
			


			List<TCC> resultados = query.list();

			getSession().close();
			
			if (resultados != null)
				return resultados;

		} catch (Exception e) {
			e.printStackTrace();
		}

		return null;
	}
	
	public TCC getProjetoByAuthor(Usuario user) {
		TCC resultado = null;
		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH a.curso JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador LEFT JOIN FETCH t.participacoes AS p  LEFT JOIN FETCH p.professor WHERE t.aluno = :user AND t.projeto = :projeto");
			query.setParameter("user", user);
			query.setParameter("projeto", true);


			resultado = (TCC) query.uniqueResult();

			getSession().close();

		} catch (Exception e) {
			e.printStackTrace();
		}

		return resultado;
	}
	
	public List<TCC> getProjetosByCurso(Curso curso) {
		try {
			Query query = getSession()
					.createQuery(
							"SELECT t FROM TCC AS t JOIN FETCH t.aluno AS a JOIN FETCH t.orientador LEFT JOIN FETCH t.coOrientador WHERE a.curso = :curso AND t.projeto = :projeto ORDER BY t.dataEnvioFinal DESC");
			query.setParameter("curso", curso);
			query.setParameter("projeto", true);

			List<TCC> resultados = query.list();

			getSession().close();

			if (resultados != null)
				return resultados;

		} catch (Exception e) {
			e.printStackTrace();
		}

		return null;
	}
	

4) Com o TCCDao Pronto finalmente podemos ir para o próximo passo, o acesso a criação do projeto:

Ao lado do botão que se cria um novo trabalho eu foi adicionado o novo projeto

O conjunto em tccs-curso.zul ficou:

(linha 46)<div style="float:right">
								<button style="float:right"
									label="Cadastrar novo Projeto" onClick="@command('novoProjeto')" />
								<button style="float:right"
									label="Cadastrar novo Trabalho" onClick="@command('novoTrabalho')" />
							</div>

e as funções especificas em TCCsCursoController que redirecionam para a mesma pagina, só que com parâmetros diferentes

@Command
	public void novoTrabalho()
	{
		SessionManager.setAttribute("projeto",false);
		SessionManager.setAttribute("novo",true);
		Executions.sendRedirect("/pages/editor.zul");
	}
	
	@Command
	public void novoProjeto()
	{
		SessionManager.setAttribute("projeto",true);
		SessionManager.setAttribute("novo",true);
		Executions.sendRedirect("/pages/editor.zul");
	}

5) Agora vamos trabalhar esses parâmetros:

a mudança do botão visualizar, ela sera usada depois para visualizar o projeto, caso

(linha 24)

<button label="Verificar" id="verifyButton"
									onClick="@command('verifyAluno', textBox=verifyTextBox,button=self,label=infoLabelAluno)"
									disabled="@load(not vm.canChangeMatricula)" visible="@load(vm.canChangeMatricula)"/>

e a mudança de:

 not vm.userSecretaria
 para 
vm.notUserSecretariaAndNotProject

 nas linhas 99,191 e 200

6) Para as funções desse zul funcionar vamos em EditorTccController e mudamos

o case Usuário.ALUNO para

TCC tempTCC = tccBusiness.getCurrentTCCByAuthor(getUsuario(), getCurrentCalendar(getUsuario().getCurso()),false);
			
			if(tempTCC == null)
				tempTCC = tccBusiness.getCurrentTCCByAuthor(getUsuario(), getCurrentCalendar(getUsuario().getCurso()),true);
			
			SessionManager.setAttribute("projeto",tempTCC.isProjeto());
			getUsuario().getTcc().clear();
			if (tempTCC != null) {
				getUsuario().getTcc().add(tempTCC);
				tcc = getUsuario().getTcc().get(0);
			} else
				redirectHome();

			canChangeOrientacao = false;
			
			break;

o verificaAluno() fica:

@NotifyChange({ "tcc", "alunoEditBlock" })
	@Command
	public void verifyAluno(@BindingParam("textBox") Textbox textb,
			@BindingParam("button") Button bt, @BindingParam("label") Label lbl) {
		
		if (bt.getLabel().equals("Verificar")) {
			lbl.setVisible(true);
			if (tcc.getAluno().getMatricula() != null
					&& tcc.getAluno().getMatricula().trim().length() > 0) {
				Usuario aluno = new UsuarioBusiness().getByMatricula(tcc
						.getAluno().getMatricula().trim());
				if (aluno != null) {
					if (aluno.getTipoUsuario().getIdTipoUsuario() != Usuario.ALUNO
							|| getUsuario().getTipoUsuario().getIdTipoUsuario() != Usuario.ADMINISTRADOR
							&& aluno.getCurso().getIdCurso() != getUsuario()
									.getCurso().getIdCurso()) {
						lbl.setValue("Usuário existe mas não é um aluno ou pertence a outro curso.");
						alunoEditBlock = true;
						alunoVerified = false;
					} else {
						tcc.setAluno(aluno);
						lbl.setValue("Usuário já cadastrado.");
						alunoEditBlock = true;
						alunoVerified = true;
						textb.setReadonly(true);
						bt.setLabel("Editar");
						if(tccBusiness.getTCCsByAuthor(tcc.getAluno())!=null)
							if(tccBusiness.getTCCsByAuthor(tcc.getAluno()).size()>0)
						if(tccBusiness.getTCCsByAuthor(tcc.getAluno()).get(0).isProjeto()//botao para, quando estiver criando o trabalho visualizar o projeto
							&& !((boolean)SessionManager.getAttribute("projeto")))
							((Button)(lbl.getParent().getParent().getParent().getChildren().get(4).getChildren().get(0))).setVisible(true);
						else
						{
							if(((boolean)SessionManager.getAttribute("projeto"))//reativar o projeto
									&& ((boolean)SessionManager.getAttribute("novo"))
									&& tccBusiness.getProjetoByAuthor(tcc.getAluno())!=null)
							{
								
							    Messagebox.show("O Usuário ja possui um projeto, deseja reativa-lo?", "Alerta", Messagebox.YES|Messagebox.NO, Messagebox.QUESTION,
							    	     new EventListener() {
							    	       public void onEvent(Event evt) {
							    	         switch (((Integer)evt.getData()).intValue()) {
							    	           case Messagebox.YES: doYes(); break; 
							    	           case Messagebox.NO: doNo(); break; 
							    	      }
							    	    }
							    	   });
								
								//setar a data de envio para a banca
							}
								
						}
					}
				} else {
					if (getUsuario().getTipoUsuario().getIdTipoUsuario() != Usuario.ADMINISTRADOR) {
						alunoEditBlock = false;
						lbl.setValue("Usuário ainda não cadastrado.Faça o cadastro abaixo.");
						alunoVerified = true;
						textb.setReadonly(true);
						bt.setLabel("Editar");
					} else {
						alunoEditBlock = true;
						lbl.setValue("Usuário ainda não cadastrado.Cadastre ele no menu de Usuários.");
						alunoVerified = false;
					}
				}
			} else {
				alunoEditBlock = true;
				lbl.setValue("É necessário digitar a matrícula.");
				alunoVerified = false;
			}
		} else {
			alunoEditBlock = true;
			alunoVerified = false;
			lbl.setVisible(false);
			textb.setReadonly(false);
			textb.setAttribute("readonly", false);
			bt.setLabel("Verificar");
		}
	}

Duas funções para o funcionamento do Message.show

	private void doYes()
	{
		TCC tccAux = tccBusiness.getProjetoByAuthor(tcc.getAluno());
		tccAux.setDataEnvioBanca(new Timestamp(new Date().getTime()));
		tccBusiness.saveOrEdit(tccAux);
		Executions.sendRedirect(null);
	}
	
	private void doNo()
	{
		Executions.sendRedirect(null);
	}

O submit() fica:

@Command("submit")
	public void submit() {
		if((SessionManager.getAttribute("novo"))!= null)
			if((boolean)(SessionManager.getAttribute("novo")))
			{
				if(tccBusiness.getCurrentTCCByAuthor(tcc.getAluno(), getCurrentCalendar(getUsuario().getCurso()),true)!=null
						&& ((boolean)SessionManager.getAttribute("projeto")))
				{
					Messagebox.show("Este usuário ja possui um projeto iniciado neste período", "Erro",
							Messagebox.OK, Messagebox.ERROR);
					return;
				}	
				else
				{
					if(tccBusiness.getCurrentTCCByAuthor(tcc.getAluno(), getCurrentCalendar(getUsuario().getCurso()),false)!=null
							&& !((boolean)SessionManager.getAttribute("projeto")))
					{
						Messagebox.show("Este usuário ja possui um trabalho iniciado neste período", "Erro",
								Messagebox.OK, Messagebox.ERROR);
						return;
					}	
				}
				
			}
		
					
		if (getUsuario().getTipoUsuario().getIdTipoUsuario() == Usuario.SECRETARIA
				&& (tcc.getArquivoTCCFinal() == null && !tccFileChanged)) {
			Messagebox.show("É necesário enviar o documento PDF.", "Erro",
					Messagebox.OK, Messagebox.ERROR);
			return;
		}
		if (getUsuario().getTipoUsuario().getIdTipoUsuario() != Usuario.ALUNO
				&& (canChangeMatricula && !alunoVerified)) {
			Messagebox
					.show("Antes de enviar é necesário validar a matricula do aluno no botão de verificar.",
							"Erro", Messagebox.OK, Messagebox.ERROR);
			return;
		}

		tcc.setDataEnvioBanca(new Timestamp(new Date().getTime()));
		if (tccBusiness.validate(tcc)) {

			if (!alunoEditBlock) {
				UsuarioBusiness usuarioBusiness = new UsuarioBusiness();
				if (usuarioBusiness.validate(tcc.getAluno(), null, false)) {
					tcc.getAluno().setSenha(
							usuarioBusiness.encripta(usuarioBusiness
									.generatePassword()));
					TipoUsuario aluno = new TipoUsuario();
					aluno.setIdTipoUsuario(Usuario.ALUNO);
					tcc.getAluno().setTipoUsuario(aluno);
					if (!usuarioBusiness.salvar(tcc.getAluno())) {
						Messagebox
								.show("Devido a um erro, o Autor não foi cadastrado.",
										"Erro", Messagebox.OK, Messagebox.ERROR);
						return;
					}
				} else {
					String errorMessage = "Aluno:\n";
					for (String error : usuarioBusiness.getErrors())
						errorMessage += error;
					Messagebox.show(errorMessage,
							"Dados insuficientes / inválidos", Messagebox.OK,
							Messagebox.ERROR);

					return;
				}
			}
			
			tcc.setProjeto(((boolean)SessionManager.getAttribute("projeto")));
			tcc.setCalendarioSemestre(getCurrentCalendar(tcc.getAluno().getCurso()));
			
			if (tccFileChanged && tccFile != null) {
				savePDF();
				tccFileChanged = false;
				try {
					tccFile.close();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				tccFile = null;
			} else if (getUsuario().getTipoUsuario().getIdTipoUsuario() != Usuario.SECRETARIA
					&& tcc.getArquivoTCCBanca() == null)
				Messagebox
						.show("Você não enviou o documento PDF. Lembre-se de enviá-lo depois.",
								"Aviso", Messagebox.OK, Messagebox.INFORMATION);

			if (extraFileChanged && extraFile != null) {
				saveExtraFile();
				extraFileChanged = false;
				try {
					extraFile.close();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				extraFile = null;
			}

			if (tccBusiness.saveOrEdit(tcc)) {
				Messagebox.show("TCC atualizado com sucesso!");

				if (!new ParticipacaoBusiness().updateList(tcc)) {
					Messagebox
							.show("Não foi possível salvar as alterações da Banca Examinadora.",
									"Erro", Messagebox.OK, Messagebox.ERROR);
					return;
				}

			} else {
				Messagebox.show("Devido a um erro, o TCC não foi cadastrado.",
						"Erro", Messagebox.OK, Messagebox.ERROR);
			}

		} else {
			String errorMessage = "";
			for (String error : tccBusiness.getErrors())
				errorMessage += error;
			Messagebox.show(errorMessage, "Dados insuficientes / inválidos",
					Messagebox.OK, Messagebox.ERROR);
		}
	}

e finalmente são adicionadas outras funções de acesso, acabando essa classe:

public boolean isProjeto()
	{
		return ((boolean)SessionManager.getAttribute("projeto"));
	}
	
	public boolean getPossuiProjeto()
	{
		if(tccBusiness.getCurrentTCCByAuthor(tcc.getAluno(), getCurrentCalendar(tcc.getAluno().getCurso()), true)!=null)
			return true;
		return false;
	}
	
	public boolean isNotUserSecretariaAndNotProject()
	{
		return !isUserSecretaria() && !((boolean)SessionManager.getAttribute("projeto"));
	}

	@Command
	public void verificarProjeto()
	{
		TCC projeto = tccBusiness.getCurrentTCCByAuthor(tcc.getAluno(), getCurrentCalendar(tcc.getAluno().getCurso()), true);
		SessionManager.setAttribute("tccId",projeto.getIdTCC());
		Window window = (Window) Executions.createComponents(
				"/pages/projeto.zul", null, null);
		window.doModal();
	}

7) Para a visualização do Aluno precisamos mudar o menu-aluno.zul:

(linha 9)
<menuitem label="@load(hf.meuX)" onClick="@command('myTcc')" />

e vamos para o controlador dele MenuController

O myTcc() fica da seguinte maneira

@Command
	public void myTcc() {
		TCCBusiness tccB = new TCCBusiness();
		List<TCC>  tccs = tccB.getTCCsByAuthor(getUsuario());
		
		getUsuario().setTcc(tccs);
		
		if (getUsuario() != null
				&& getUsuario().getTipoUsuario().getIdTipoUsuario() == Usuario.ALUNO) {
			if (getCurrentCalendar() != null) {
				if (getUsuario().getTcc() != null && getUsuario().getTcc().size() != 0)
					Executions.sendRedirect("/pages/editor.zul");
				else
					Messagebox
							.show("Você ainda não possui um Trabalho cadastrado no semestre atual.\n Entre em contato com o coordenador do curso.",
									"Erro", Messagebox.OK, Messagebox.ERROR);
			} else {
				Messagebox.show(
						"Não há nenhum Calendário cadastrado no Sistema!",
						"Erro", Messagebox.OK, Messagebox.ERROR);
			}
		}
	}

o  changeProfile(int) também muda:

	@SuppressWarnings("unchecked")
	public void changeProfile(int index) {
		users = (List<Usuario>) SessionManager.getAttribute("usuarios");
		if (index < users.size()) {
			SessionManager.setAttribute("usuario", users.get(index));
			getUsuario().getTipoUsuario().setPermissoes(
					new PermissaoBusiness()
							.getPermissaoByTipoUsuario(getUsuario()
									.getTipoUsuario()));

			if (getUsuario().getTipoUsuario().getIdTipoUsuario() == Usuario.ALUNO) {
				TCCBusiness tccBusiness = new TCCBusiness();
				
				TCC tempTcc = tccBusiness.getCurrentTCCByAuthor(getUsuario(), getCurrentCalendar(getUsuario().getCurso()),false);
				if(tempTcc == null)
					tempTcc = tccBusiness.getCurrentTCCByAuthor(getUsuario(), getCurrentCalendar(getUsuario().getCurso()),true);
				
				List<TCC> tccs = new ArrayList<TCC>();
				if (tempTcc != null)
					tccs.add(tempTcc);
				getUsuario().setTcc(tccs);
			}

			redirectHome();
		}
	}
e é adicionada a função 

	public String getMeuX()
	{
		TCCBusiness tccBusiness = new TCCBusiness();	
		if(!tccBusiness.getTCCsByAuthor(getUsuario()).get(0).isProjeto())
			return "Meu Trabalho";
		else
			return "Meu Projeto";
	}

8)Finalmente, para a visualização é mudada a função init do VisualizaController

@Init
	public void init() {
		String tccId = Executions.getCurrent().getParameter("id");
		if(tccId == null)
		{
			tccId = Integer.toString((int)SessionManager.getAttribute("tccId"));
			SessionManager.setAttribute("tccId",-1);
		}
		
		if (tccId != null) {
			TCCBusiness tccBusiness = new TCCBusiness();
			tcc = tccBusiness.getTCCById(Integer.parseInt(tccId));
		}
		if (tcc != null && canViewTCC()) {
			if (getUsuario() != null && checkLogin()) {
				if (canAnswer) {
					List<Pergunta> questions = new PerguntaBusiness()
							.getQuestionsByQuestionary(new QuestionarioBusiness()
									.getCurrentQuestionaryByCurso(tcc
											.getAluno().getCurso()));

					Participacao p = null;
					for (Participacao aux : getUsuario().getParticipacoes()) {
						if (aux.getTcc().getIdTCC() == tcc.getIdTCC())
							p = aux;
					}

					for (Pergunta question : questions) {
						Resposta answer = new Resposta();
						answer.setPergunta(question);
						answer.setParticipacao(p);
						answers.add(answer);
					}
				}

			}
		} else
			redirectHome();

	}

e adicionado um novo zul, exclusivo para o projeto:

o projeto.zul que é bem parecido com o visualiza, só que é uma janela, e é voltado para projetos:

<?page title="Visualizar Trabalho" contentType="text/html;charset=UTF-8"?>
<?script content="zk.useStack='auto'" ?>
<zk>
<window width="80%" height="80%"
		title="Projeto" border="normal"
		closable="true">

	<style src="/style.css" />
	<div apply="org.zkoss.bind.BindComposer"
		viewModel="@id('vm') @init('br.ufjf.tcc.controller.VisualizaTCCController')"
		style="background-color:#efefef;" height="94.3%">
		<div height="100%">
			<div height="100%" width="30%"
				style="padding: 10px;float: left;background-color:#efefef;">
				<tabbox id="tb" height="100%">
					<tabs id="tabs" height="100%">
						<tab id="A" label="Informações do Trabalho" />
						<tab id="B" label="Preencher ficha de respostas"
							visible="@load(vm.canAnswer ? 'true' : 'false')" />
					</tabs>
					<tabpanels height="100%">
						<tabpanel height="100%"
							style="overflow:scroll;">
							<div
								onCreate="@command('setInformacoes', adiv=self)">
								<label value="Título"
									style="font-size: 14px; font-weight: bold; margin-top:5px;" />
								<label value="@load(vm.tcc.nomeTCC)" />
								<label value="Subtítulo"
									visible="@load(not empty vm.tcc.subNomeTCC)"
									style="font-size: 14px; font-weight: bold; margin-top:5px;" />
								<label value="@load(vm.tcc.subNomeTCC)" />
								<label value="Autor"
									style="font-size: 14px; font-weight: bold; margin-top:5px;" />
								<label
									value="@load(vm.tcc.aluno.nomeUsuario)" />
								<label value="Orientador"
									style="font-size: 14px; font-weight: bold; margin-top:5px;" />
								<label
									value="@load(vm.tcc.orientador.nomeUsuario)" />
								<label value="Co-Orientador"
									visible="@load(not empty vm.tcc.coOrientador)"
									style="font-size: 14px; font-weight: bold; margin-top:5px;" />
								<label
									value="@load(vm.tcc.coOrientador.nomeUsuario)" />
								<label value="Resumo"
									visible="@load(not empty vm.tcc.resumoTCC)"
									style="font-size: 14px; font-weight: bold; margin-top:5px;" />
								<label value="@load(vm.tcc.resumoTCC)" style="text-align:justify;"/>
								<div style="margin-top:5px">
									<label value="Ano:  "
										style="font-weight:bold;float:left" />
									<label
										onCreate="@command('getTccYear', lbl=self)"
										style="padding-left: 30px;" />
								</div>
								<label value="Palavras-chave"
									visible="@load(not empty vm.tcc.palavrasChave)"
									style="font-size: 14px; font-weight: bold; margin-top:5px" />
								<label
									value="@load(vm.tcc.palavrasChave)" />
								<div
									style="cursor: pointer; margin-top:10px"
									visible="@load(vm.canDonwloadFileBanca and not empty vm.tcc.arquivoTCCBanca ? 'true' : 'false')"
									onClick="@command('downloadPDFBanca', tcc=each)">
									<image src="/img/pdf.png" />
									<label value="Obter PDF (Banca)"
										style="font-size: 14px; font-weight: bold; float:left;margin:5px;" />
								</div>
								<div
									style="cursor: pointer; margin-top:10px"
									visible="@load(not empty vm.tcc.arquivoTCCFinal ? 'true' : 'false')"
									onClick="@command('downloadPDF', tcc=each)">
									<image src="/img/pdf.png" />
									<label value="Obter PDF"
										style="font-size: 14px; font-weight: bold;float: left;margin:5px;" />
								</div>
								<div
									style="cursor: pointer; margin-top:10px"
									visible="@load(not empty vm.tcc.arquivoExtraTCCFinal ? 'true' : 'false')"
									onClick="@command('downloadExtra', tcc=each)">
									<image src="/img/rar.png" />
									<label value="Obter arquivos extras"
										style="font-size: 14px; font-weight: bold;float: left;margin:5px;" />
								</div>
							</div>




						</tabpanel>
						<tabpanel
							visible="@load(vm.canAnswer ? 'true' : 'false')" height="100%"
							style="overflow:scroll;">
							<div visible="false"
								onCreate="@command('setFicha', adiv=self)">
								<grid model="@load(vm.answers)"
									style="margin:10px;">
									<columns>
										<column />
										<column width="125px" />
									</columns>
									<template name="model">
										<row>
											<div>
												<label
													value="Pergunta ${forEachStatus.index + 1}: " />
												<label
													value="@load(each.pergunta.titulo)" />
												<label value=" (" />
												<label
													value="@load(each.pergunta.valor)" />
												<label value=" pts )" />
											</div>
											<div>
												<label
													value="Resposta: " />
												<textbox
													value="@bind(each.nota)" width="95%" />
											</div>
										</row>
									</template>
								</grid>
								<div align="center">
									<button label="Cadastrar Respostas"
										onClick="@command('submitFicha', window=prquest)"
										style="margin-bottom:10px;" />
								</div>
							</div>
						</tabpanel>
					</tabpanels>
				</tabbox>

			</div>
			<div style="float: left;width: 70%; height: 100%;">
				<iframe autohide="true" height="100%" width="100%"
					onCreate="@command('showTCC', iframe=self)" />
			</div>
		</div>
	</div>
	</window>
</zk>
