### ISSUE TITLE
Erro ao ordenar listagem de professores

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#131]
Ao ordenar os professores cadastrados clicando na coluna de departamento ou curso, a ordem não se dá de acordo com o nome do departamento/curso. Vide a posição dos professores cadastrados como departamento CGCO.

**Comment by fanuelson** [comment]
Acredito que esteja corrigido Jairo.

**Comment by jairofsouza** [comment]
Só tenho a agradecer!!!

Abs,
Jairo

**Comment by fanuelson** [comment]
@jairofsouza essa issue tbm foi corrigida jairo. Antes de fechar favor verificar.

**Comment by jairofsouza** [comment]
Foi testado e está ok.
