### ISSUE TITLE
Colocar link do sistema no email que vai para a banca

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#138]

**Comment by fanuelson** [comment]
Boa Noite jairo,
É pra colocar o link do sistema em todos os e-mails ?
Se não em quais ?

EmailProjetoCriado
EmailChainPAA
EmailChainTAACoordenador
EmailChainTAAProfessor
EmailChainTrabFinal

**Comment by jairofsouza** [comment]
@fanuelson apenas no email que vai pros professores quando o aluno marca a banca (EmailChainTAAProfessor?) e quando o trabalho final é submetido (EmailChainTrabFinal?)

**Comment by fanuelson** [comment]
@jairofsouza Ok, pq não colocamos o link do sistema em todos?

vc diz o link: 
http://www.monografias.ice.ufjf.br/tcc-web/
?

**Comment by jairofsouza** [comment]
Pode ser tb :)

Na verdade é o link correto é http://www.monografias.ice.ufjf.br
<http://www.monografias.ice.ufjf.br/tcc-web/>   (o outro é direcionado)

Abs,
Jairo
