### ISSUE TITLE
Informações de Upload de PDF e Extras

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#14]
Ao enviar arquivos, é preciso informar ao usuário que foram corretamente enviados, pois ele fica em duvida, uma vez que nada é informado.

**Comment by lucaslarcher** [comment]
Colocar um Messagebox.show() nas funções upload(Event) e extraUpload(Event)
Ps.: o arquivo faz o upload, confirma e só depois carrega o arquivo na tela, pode dar a impressão que não foi feito em um arquivo maior por exemplo o upload ainda mas já foi.
Alem disso tem a barra de upload já implementada.
