### ISSUE TITLE
Retirar termo "TCC" do sistema

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#16]
O termo TCC não deve ser usado. Alterar para "Trabalho". 
Na lista pública, por exemplo, uma coluna ainda está com o título NomeTCC.

**Comment by jairofsouza** [comment]
Mensagem "	TCC atualizado com sucesso!" ao salvar o projeto de tcc ....

**Comment by lucaslarcher** [comment]
Fica em EditorTccController na função submit
