### ISSUE TITLE
Alterar lista de cursos na home

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#21]
Quando cursos são cadastrados no sistema, eles aparecem na home do sistema. Contudo, alguns cursos são cadastrados e não possuem nenhuma monografia. Permitir que apareçam somente cursos que possuem pelo menos 1 monografia cadastrada.

PS: apagar a monografia TESTETITULO que está cadastrada para o curso de pos-graduação em ciencia da computação.

**Comment by lucaslarcher** [comment]
pode melhorar usando algum comendo sql para pegar so os cursos que tem mais de 0 TCC, mas eu não consegui ainda
