### ISSUE TITLE
No filtro de curso, colocar "todos (trabalhos mais recentes)"

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#24]

**Comment by lucaslarcher** [comment]
Fica em ListaPublicController na função getAllCursos() e lembrar da verificação em changeCurso()

**Comment by jairofsouza** [comment]
Label do combox ainda está errado.

**Comment by lucaslarcher** [comment]
no index.zul renomear tambem o value do combobox
linha 27
