### ISSUE TITLE
Acesso de aluno

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#26]
Se acabou o semestre, o aluno deixa de ser ativo e perde o acesso ao sistema. Os dados dele continuam no sistema, mas ele não tem mais acesso.

Quando começar o semestre, o coordenador marca quem são os alunos ativos daquele semestre. A partir dai, os alunos vão cadastrar o seu projeto de tcc.

**Comment by lucaslarcher** [comment]
Para ativar os usuários, clicar no checkbox do editar-usuario.zul, depois das seguintes mudanças:

editar o edit-usuario.zul
(linha 145)
 <checkbox checked="@load(each.ativo)"
						disabled="false" onClick="@command('mudarAtivo',check=self,usuario=each)"/>

e em GerenciamentoUsuarioController adicionar a função:

	@Command
	public void mudarAtivo(@BindingParam("check") final Checkbox check,@BindingParam("usuario") final Usuario usuario)
	{
		String mensagem;
		if(usuario.isAtivo())
			mensagem = "Tem certeza que deseja destivar o usuário?";
		else
			mensagem = "Tem certeza que deseja ativar o usuário?";
			
		Messagebox.show(mensagem, "Confirmação", Messagebox.YES | Messagebox.NO, Messagebox.QUESTION, new org.zkoss.zk.ui.event.EventListener() {
		    public void onEvent(Event evt) throws InterruptedException {
		        if (evt.getName().equals("onYes")) {
					usuario.setAtivo(check.isChecked());
					usuarioBusiness.editar(usuario);
		        } 
		        else
		        	check.setChecked(usuario.isAtivo());
		    }
		});
	}
