### ISSUE TITLE
Erro ao abrir trabalho de aluno

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#27]
Quando o coordenador abre a tela de edição do trabalho do aluno e salva, o sistema pede pra validar a matricula do aluno. Não é necessário pq a matricula não foi alterada. Aliás, a matricula deveria ficar inacessível.

**Comment by lucaslarcher** [comment]
No submit do EditorTCCController mudar o if usuario aluno:

(linha 414)

if (getUsuario().getTipoUsuario().getIdTipoUsuario() != Usuario.ALUNO
				&& (tcc.getAluno()==null)) {
