### ISSUE TITLE
Edição de projeto de tcc

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#30]
Ao cadastrar novo projeto (trabalho), o aluno vai preencher o orientador, titulo, resumo e palavras-chave. Todo o resto fica inacessível (ou oculto) pra ele.

**Comment by lucaslarcher** [comment]
Mudar o visible do hlayout da data de apresentação e sala de defesa para 

visible="@load(not vm.userSecretaria and not vm.project)"

linhas 185 e 194

alem disso o bancaForm tambem deve estar com o mesmo visible

linha 93
