### ISSUE TITLE
Tela com relação de trabalhos

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#32]
Deveria primeira aparecer marcado todos (projetos e trabalhos)
Colocar uma coluna para ver quem é o orientador
Colocar uma coluna com data de envio
Colocar uma coluna para saber o status do trabalho 
    -> Projeto incompleto    PI
    -> Projeto aguarda aprovação PAA
    -> Trabalho incompleto        TI
    -> Trabalho aguarda aprovação  TAA
   
Para os status, criar siglas e colocar como legenda (usar o ?)

**Comment by lucaslarcher** [comment]
Criar uma função no TCCBussiness

	public String getStatusTCC(TCC tcc)
	{
		if(isProjetoAguardandoAprovacao(tcc))
			return "PAA";
		else
		if(isProjetoIncompleto(tcc))
			return "PI";
		else
		if(isTrabalhoAguardandoAprovacao(tcc))
			return "TAA";
		else
		if(isTrabalhoIncompleto(tcc))
			return "TI";
		else
			return "Aprovado";
	}

Criar uma função no TCC

public String getStatusTCC()
	{
		return (new TCCBusiness()).getStatusTCC(this);
	}

e agora mudar o tcc-cursos, a partir do inicio do collumns ate o final substituir por:

(linha 89)

<columns>
				<column hflex="10" label="Titulo" sort="auto(nomeTCC)" />
				<column hflex="4" label="Autor"
					sort="auto(aluno.nomeUsuario)" />
				<column hflex="4" label="Orientador" />
				<column hflex="4" label="Data e horário de Envio" />
				<column hflex="2" label="Status" image="/img/help.gif"
					tooltip="filterStatus" style="cursor: help" />
				<column hflex="1" label="PDF" />
				<column hflex="1" label="Extras" />
			</columns>
			<template name="lista">
				<row xmlns:w="client"
					w:onClick="visualzarTCC(${each.idTCC});"
					tooltip="${forEachStatus.index}, position=at_pointer">
					<div>
						<label value="@load(each.nomeTCC)" />
						<popup id="${forEachStatus.index}">
							<vlayout width="550px">
								<label value="Resumo"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label value="@load(each.resumoTCC)" />
								<hlayout>
									<label value="Ano: "
										style="font-weight:bold;" />
									<label
										onCreate="@command('getEachTccYear', tcc=each, lbl=self)" />
								</hlayout>
								<label value="Orientador"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label
									value="@load(each.orientador.nomeUsuario)" />
								<label value="Palavras-chave"
									visible="@load(not empty each.palavrasChave)"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label
									value="@load(each.palavrasChave)" />
							</vlayout>
						</popup>
					</div>
					<label value="@load(each.aluno.nomeUsuario)" />
					<label value="@load(each.orientador.nomeUsuario)" />
					<label value="@load(each.dataEnvioBanca)" />
					<label value="@load(each.statusTCC)" />
					<image src="/img/pdf.png" style="cursor: pointer"
						onClick="@command('downloadPDF', tcc=each)" />
					<image style="cursor: pointer"
						src="@load(not empty each.arquivoExtraTCCFinal ? '/img/rar.png' : '/img/norar.png')"
						onClick="@command('downloadExtra', tcc=each)" />
				</row>
			</template>
		</grid>
	</div>
	<popup id="filterHelp">
		<html>
			<![CDATA[ Permite filtrar a lista de Trabalhos  com os seguintes filtros:
			<ul><li>Semestre atual ou todos os semstres;</li> <li>Estados (PI,PAA,TI,TAA);</li>
			<ul>]]>
		</html>
	</popup>
	
	<popup id="filterStatus">
		<html>
			<![CDATA[ Status:
			<ul><li>PI - Projeto incompleto</li>
			<li>TI - Trabalho incompleto</li>
			<li>PAA - Projeto aguardando aprovação</li>
			<li>TAA - Trabalho aguardando aprovação</li>
			<ul>]]>
		</html>
	</popup>
</zk>
