### ISSUE TITLE
Alterar botão "Verificar projeto"

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#33]
Trocar para "aprovar projeto de TCC"
Dar maior destaque ao botão.

**Comment by jairofsouza** [comment]
Ao aprovar, sair da tela e voltar pra relação de trabalhos.

**Comment by jairofsouza** [comment]
Depois de aprovar o projeto, quando o aluno vai editar o trabalho, não dá pra ele colocar a banca.

**Comment by jairofsouza** [comment]
Quando o aluno altera o trabalho, na tela anterior volta a aparecer como Meu Projeto.

**Comment by lucaslarcher** [comment]
Alterar os botoes:

(linha 90)
<button image="/img/confirm.gif" label="Aprovar projeto de TCC" visible="@load(vm.projeto and vm.projetoAguardandoAprovacao)" onClick="@command('finalizaProjeto')"  width="100%"
								height="30px" style="margin-top:10px"/>
								<button image="/img/confirm.gif" label="Aprovar trabalho de TCC" visible="@load(not vm.projeto and vm.trabalhoAguardandoAprovacao)" onClick="@command('finalizaTrabalho')"  width="100%"
								height="30px" style="margin-top:10px" />

Para redirecionar para a a pagina, em finalizaTrabalho e finalizaProjeto de VisualizaTCCController
mudar o redirectHome() para 

 SessionManager.setAttribute("trabalhos_semestre",true);
	    Executions.sendRedirect("/pages/tccs-curso.zul");

e para quando atualizar/confirmar do editar, e o trabalho voltar pra home, mude o submit do EditorTCCController, mudar o if:

(linha 497)
if (tccBusiness.saveOrEdit(tcc)) {
				String alerta;
				if(tcc.isProjeto())
					alerta = "Projeto salvo!";
				else
					alerta = "Trabalho salvo;";
				Messagebox.show(alerta, "Confirmação", Messagebox.OK , Messagebox.EXCLAMATION, new org.zkoss.zk.ui.event.EventListener() {
				    public void onEvent(Event evt) throws InterruptedException {
				        if (evt.getName().equals("onOK")) {
				        	redirectHome();
				        } 
				    }
				});

				
				if (!new ParticipacaoBusiness().updateList(tcc)) {
					Messagebox
							.show("Não foi possível salvar as alterações da Banca Examinadora.",
									"Erro", Messagebox.OK, Messagebox.ERROR);
					
					return;
				}
			

			}

A questao de "Depois de aprovar o projeto, quando o aluno vai editar o trabalho, não dá pra ele colocar a banca." e "Quando o aluno altera o trabalho, na tela anterior volta a aparecer como Meu Projeto." funcionaram em meus últimos testes, talvez por que ele foi corrigido em outra correçãofeita
