### ISSUE TITLE
Trabalhos passados

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#35]
O coordenador tem que ter acesso a trabalhos passados para atualizar, aprovar e enviar PDF mesmo fora do período.
O coordenador tem que ter direito a apagar trabalhos/projetos.

**Comment by lucaslarcher** [comment]
Criar uma função no TCCBussiness

	public String getStatusTCC(TCC tcc)
	{
		if(isProjetoAguardandoAprovacao(tcc))
			return "PAA";
		else
		if(isProjetoIncompleto(tcc))
			return "PI";
		else
		if(isTrabalhoAguardandoAprovacao(tcc))
			return "TAA";
		else
		if(isTrabalhoIncompleto(tcc))
			return "TI";
		else
			return "Aprovado";
	}

Criar uma função no TCC

public String getStatusTCC()
	{
		return (new TCCBusiness()).getStatusTCC(this);
	}

e agora mudar o tcc-cursos, a partir do inicio do collumns ate o final substituir por:

(linha 89)

<columns>
				<column hflex="10" label="Titulo" sort="auto(nomeTCC)" />
				<column hflex="4" label="Autor"
					sort="auto(aluno.nomeUsuario)" />
				<column hflex="4" label="Orientador" />
				<column hflex="4" label="Data e horário de Envio" />
				<column hflex="2" label="Status" image="/img/help.gif"
					tooltip="filterStatus" style="cursor: help" />
				<column hflex="1" label="PDF" />
				<column hflex="1" label="Extras" />
			</columns>
			<template name="lista">
				<row xmlns:w="client"
					w:onClick="visualzarTCC(${each.idTCC});"
					tooltip="${forEachStatus.index}, position=at_pointer">
					<div>
						<label value="@load(each.nomeTCC)" />
						<popup id="${forEachStatus.index}">
							<vlayout width="550px">
								<label value="Resumo"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label value="@load(each.resumoTCC)" />
								<hlayout>
									<label value="Ano: "
										style="font-weight:bold;" />
									<label
										onCreate="@command('getEachTccYear', tcc=each, lbl=self)" />
								</hlayout>
								<label value="Orientador"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label
									value="@load(each.orientador.nomeUsuario)" />
								<label value="Palavras-chave"
									visible="@load(not empty each.palavrasChave)"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label
									value="@load(each.palavrasChave)" />
							</vlayout>
						</popup>
					</div>
					<label value="@load(each.aluno.nomeUsuario)" />
					<label value="@load(each.orientador.nomeUsuario)" />
					<label value="@load(each.dataEnvioBanca)" />
					<label value="@load(each.statusTCC)" />
					<image src="/img/pdf.png" style="cursor: pointer"
						onClick="@command('downloadPDF', tcc=each)" />
					<image style="cursor: pointer"
						src="@load(not empty each.arquivoExtraTCCFinal ? '/img/rar.png' : '/img/norar.png')"
						onClick="@command('downloadExtra', tcc=each)" />
				</row>
			</template>
		</grid>
	</div>
	<popup id="filterHelp">
		<html>
			<![CDATA[ Permite filtrar a lista de Trabalhos  com os seguintes filtros:
			<ul><li>Semestre atual ou todos os semstres;</li> <li>Estados (PI,PAA,TI,TAA);</li>
			<ul>]]>
		</html>
	</popup>
	
	<popup id="filterStatus">
		<html>
			<![CDATA[ Status:
			<ul><li>PI - Projeto incompleto</li>
			<li>TI - Trabalho incompleto</li>
			<li>PAA - Projeto aguardando aprovação</li>
			<li>TAA - Trabalho aguardando aprovação</li>
			<ul>]]>
		</html>
	</popup>
</zk>

**Comment by lucaslarcher** [comment]
o acesso a trabalhos passados já ocorre, agora vamos a tarefa de excluir, vou criar um excluit tcc geral e utilizar por enquanto so em trabalhos nao finalizados:

primeiro novo função em ParticipacaoBusiness, adicionar a função:

	public boolean excluiLista(List<Participacao> participacoes)
	{
		return participacaoDAO.excluiLista(participacoes);
	}

agora em TCCBussines a nova função:


public boolean excluitTCC(TCC tcc)
	{
		ParticipacaoBusiness PB = new ParticipacaoBusiness();
		PB.excluiLista(PB.getParticipacoesByTCC(tcc));

		File f;
		if(tcc.getArquivoTCCFinal()!=null)
		{
			f = new File(ConfHandler.getConf("FILE.PATH")+tcc.getArquivoTCCFinal());
			if(f!=null)
				f.delete();
		}
		if(tcc.getArquivoExtraTCCFinal()!=null)
		{
			f = new File(ConfHandler.getConf("FILE.PATH")+tcc.getArquivoExtraTCCFinal());
			if(f!=null)
				f.delete();
		}
		if(tcc.getArquivoExtraTCCBanca()!=null)
		{
			f = new File(ConfHandler.getConf("FILE.PATH")+tcc.getArquivoExtraTCCBanca());
			if(f!=null)
				f.delete();
		}
		if(tcc.getArquivoTCCBanca()!=null)
		{
			f = new File(ConfHandler.getConf("FILE.PATH")+tcc.getArquivoTCCBanca());
			if(f!=null)
				f.delete();
		}
	
		if((new TCCDAO()).exclui(tcc))
			return true;
		return false;
	}

agora podemos excluir os TCCs

para colocar isso na pagina vamos em tccs-curso e criaremos uma nova coluna pra excluir e sua devida row, columns e rows ficam assim:

<columns>
				<column hflex="10" label="Titulo" sort="auto(nomeTCC)" />
				<column hflex="4" label="Autor"
					sort="auto(aluno.nomeUsuario)" />
				<column hflex="4" label="Orientador" />
				<column hflex="4" label="Data e horário de Envio" />
				<column hflex="2" label="Status" image="/img/help.gif"
					tooltip="filterStatus" style="cursor: help" />
				<column hflex="2" label="PDF" />
				<column hflex="2" label="Extras" />
				<column hflex="2" label="Excluir" />
			</columns>
			<template name="lista">
				<row xmlns:w="client"
					w:onClick="visualzarTCC(${each.idTCC});"
					tooltip="${forEachStatus.index}, position=at_pointer">
					<div>
						<label value="@load(each.nomeTCC)" />
						<popup id="${forEachStatus.index}">
							<vlayout width="550px">
								<label value="Resumo"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label value="@load(each.resumoTCC)" />
								<hlayout>
									<label value="Ano: "
										style="font-weight:bold;" />
									<label
										onCreate="@command('getEachTccYear', tcc=each, lbl=self)" />
								</hlayout>
								<label value="Orientador"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label
									value="@load(each.orientador.nomeUsuario)" />
								<label value="Palavras-chave"
									visible="@load(not empty each.palavrasChave)"
									style="font-size: 14px; font-weight: bold; text-align: justify; display: block;" />
								<label
									value="@load(each.palavrasChave)" />
							</vlayout>
						</popup>
					</div>
					<label value="@load(each.aluno.nomeUsuario)" />
					<label value="@load(each.orientador.nomeUsuario)" />
					<label value="@load(each.dataEnvioBanca)" />
					<label value="@load(each.statusTCC)" />
					<image src="/img/pdf.png" style="cursor: pointer"
						onClick="@command('downloadPDF', tcc=each)" />
					<image style="cursor: pointer"
						src="@load(not empty each.arquivoExtraTCCFinal ? '/img/rar.png' : '/img/norar.png')"
						onClick="@command('downloadExtra', tcc=each)" />
					<button image="/img/delete.png" 
						onClick="@command('excluirTCC', tcc=each)" />
				</row>


agora falta a função para alimentar isso:

em TCCsCursoController adicione a função:

	@Command
	public void excluirTCC(@BindingParam("tcc") final TCC tcc)
	{
		final String mensagem;
		if(tcc.isProjeto())
			mensagem = "Projeto";
		else
			mensagem = "Trabalho";
		
		Messagebox.show("Tem certeza que deseja excluir este "+mensagem+"?", "Confirmação", Messagebox.YES | Messagebox.NO, Messagebox.QUESTION, new org.zkoss.zk.ui.event.EventListener() {
		    public void onEvent(Event evt) throws InterruptedException {
		        if (evt.getName().equals("onYes")) {
					if((new TCCBusiness()).excluitTCC(tcc))
						Messagebox.show(mensagem, "Confirmação", Messagebox.OK, Messagebox.EXCLAMATION, new org.zkoss.zk.ui.event.EventListener() {
						    public void onEvent(Event evt) throws InterruptedException {
						        if (evt.getName().equals("onOK")) {
						        	Executions.sendRedirect(null);
						        } 
						        else
						        	Executions.sendRedirect(null);
						    }
						});
					else
						Messagebox.show("Erro!");
		        } 
		       
		    }
		});
	}
