### ISSUE TITLE
Ativar aluno

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#42]
Ao ativar aluno, colocar "Sim"/"Não" ao invés de "Yes"/"no"

**Comment by jairofsouza** [comment]
Parece que depende da linguagem do browser... teria como forçar?

**Comment by fanuelson** [comment]
Jairo, acho que esta issue já está resolvida.

**Comment by jairofsouza** [comment]
Por que você acha?

**Comment by fanuelson** [comment]
já está aparecendo Sim/Não no messageBox quando ativa ou desativa um aluno.

**Comment by jairofsouza** [comment]
Como falei lá na issue, isso tá dependente da linguagem do browser. De vez em qdo não resolve. Mas essa issue não é urgente. Urgente é você resolver aquelas outras. Melhor focar em 1 issue só por vez ao invés de ficar passando de uma pra outra.
