### ISSUE TITLE
Cadastrar usuário secretaria

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#44]
Tem que poder cadastrar a senha também.

**Comment by lucaslarcher** [comment]
adicionar a linha para senha no gerenciamente-usuarios.zul

(linha 222)
	<row>
						<label value="Senha:" />
						<textbox id="senha"
							value="@bind(vm.newUsuario.senha)"
							tabindex="1" width="100%"/>
					</row>

e mudar o que será visualizado no onChande do combobox cmbTipoUsuario

(linha 171)
	onChange="@command('typeChange', titu=txtTitu, comboc=comboCurso, combod=comboDepartamento, label=login, senha=senha)"

agora para alimentar isso vamos no GerenciamentoUsuarioController

na função typeChange

vamos adicionar mais um parametro

@BindingParam("senha") Textbox textSenha

e  em todos os cases colocar:

textSenha.getParent().setVisible(false);

a não ser no case Usuario.SECRETARIA, que deve se colocar o 

textSenha.getParent().setVisible(true);

na função submitUser

depois do if do validate, trocar a geração de senha por:

if(newUsuario.getSenha()!=null)
									{
										newUsuario.setSenha(usuarioBusiness
												.encripta(newUsuario.getSenha()));
									}
									else
									{
										String newPassword = usuarioBusiness
												.generatePassword();
										newUsuario.setSenha(usuarioBusiness
												.encripta(newPassword));
									}
