### ISSUE TITLE
Processo de criação de projetos / Trabalhos

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#49]
- O status do projeto quando falta palavra-chave aparece como PAA mas deveria ser PI.
- Colocar como mensagem para o aluno que o trabalho dele falta palavra chave.
- As mensagens: É necessário informar a Data de Apresentação; É necessário informar a sala de Apresentação; É necessário informar a Banca, etc, não precisam ter palavras em maiúsculo.

**Comment by jairofsouza** [comment]
Ao criar a banca, posso também ter professores de outro departamento.

**Comment by lucaslarcher** [comment]
No getInfo de HomeAlunoControler é preciso fazer a verificação e no TCCBusiness de palavras chave, alem é claro de colocar os termos da em minusculo ainda no tccBisuness

**Comment by jairofsouza** [comment]
Essa issue precisa ser testada na versão de desenvolvimento. Esta issue está relacionada com a issue #54.
