### ISSUE TITLE
Colocar um filtro Secretaria na tela de Gerenciar Usuários de adminstrador e de coordenador.

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#51]

**Comment by jairofsouza** [comment]
Na tela de coordenador não precisa aparecer o filtro de Administrador e Professor, já que o coordenador não tem direito de editar esses usuários.

**Comment by lucaslarcher** [comment]
em gerenciamento-usuario.zul nos raios professor e administrador colocar:

(linha 39)
visible="@load(not vm.coordenador)"


e para alimentar isso, em  GerenciamentoUsuarioController adicionar a função:

	public boolean isCoordenador()
	{
		if(getUsuario()!=null)
			if(getUsuario().getTipoUsuario().getIdTipoUsuario() == Usuario.COORDENADOR)
				return true;
		return false;
	}

**Comment by jairofsouza** [comment]
A issue não foi toda resolvida: ainda falta colocar o filtro secretaria na tela.
