### ISSUE TITLE
Ao editar trabalhos, o PDF já enviado não aparece

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#53]
Para reproduzir:
   - Logue como secretário
   - Clique em Gerenciar Trabalho e abra uma monografia (o pdf irá aparecer ao lado)
   - Clique em Editar Trabalho 

   O PDF anteriormente enviado não aparecerá.

**Comment by fanuelson** [comment]
essa issue tbm está resolvida.

**Comment by jairofsouza** [comment]
Testado e confirmo que funcionou.
