### ISSUE TITLE
Relatório de trabalhos aparecerem trabalhos já terminados

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#54]
Ao clicar em Gerenciar Trabalhos aparece uma lista de trabalhos como TI (trabalho incompleto). Contudo, são trabalhos completos cadastrados pela secretária do curso. 
   Por que esses trabalhos estão aparecendo como incompletos? Repensar os testes que são realizados.

**Comment by fanuelson** [comment]
Jairo, então a secretaria só cadastra trabalhos completos. Portanto quando ela cadastrar um trabalho ele pode ser TI se ela n preencheu todos devidamente ou TAA se ela preencheu tudo.

**Comment by jairofsouza** [comment]
Não. Quando a secretária cadastra, tem que ir direto para Aprovado. A secretária não vai preencher campo como data de defesa e banca porque ela não terá essas informações. Então, no caso dela, tem q ir direto para Aprovado. Quando que as demais informações são obrigatórias dela preencher.

**Comment by fanuelson** [comment]
Issue resolvida?
