### ISSUE TITLE
Um usuário cadastrado como professor pode virar coordenador de algum curso

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#56]
Ao cadastrar usuário coordenador, se já tiver um professor cadastrado no sistema, não consigo informar que esse professor será o coordenador do curso. Ao cadastrar o coordenador com os dados do professor, dá erro pois id já foi cadastrado.

 Considerando que todo coordenador é um professor, então o coordenador não deveria ser um usuário, mas um perfil de usuário. Deveríamos somente selecionar um professor e dizer que ele é coordenador.

**Comment by fanuelson** [comment]
Jairo, vou criar uma opção para o administrador poder escolher o coordenador do curso "x".
Quando escolhido esse coordenador, eu tenho que tirar o tipo coordenador do antigo certo?

**Comment by jairofsouza** [comment]
Fanuel, se não tiver essa restrição no banco de dados, não tem problema o curso ter mais de 2 coordenadores. Então vc pode colocar uma opção para transformar alguém em coordenador e para tirar a função de coordenador de alguém tb.

**Comment by jairofsouza** [comment]
Colocar um botão para alterar a função ao invés de usar um combobox.

**Comment by fanuelson** [comment]
Jairo, somente o administrador pode fazer essa alteração?

**Comment by jairofsouza** [comment]
Exato, somente o administrador.
