### ISSUE TITLE
Mensagem errada

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#57]
Na tela de Gerenciar Trabalhos, quando não tem nenhum trabalho cadastrado, aparece a mensagem "Não há TCCs válidas para esses filtros". Não deveria aparecer a palavra TCC (deveria ser "trabalho").

**Comment by jairofsouza** [comment]
A melhor mensagem seria "Não foram encontrados trabalhos cadastrados"

**Comment by fanuelson** [comment]
Issue concertada.
