### ISSUE TITLE
Gerar arquivos Bibtex para as monografias

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#61]
Na tela de visualização de monografias deveria aparecer o bibtex de cada monografia.
Essa issue está relacionada com a #12

**Comment by jairofsouza** [comment]
Acentuação do latex está errada.

**Comment by jairofsouza** [comment]
Lembrar de verificar se nomes estão com o problema dos acentos resolvidos. Nomes como Átila aparecem no formato látex corretamente (A maiúsculo)?

**Comment by jairofsouza** [comment]
OK

**Comment by jairofsouza** [comment]
No Bibtex, ao invés de colocar o endereço da monografia com IP (http://200.131.219.47/), coloque o domínio correto (http://monografias.ice.ufjf.br/)

**Comment by fanuelson** [comment]
Issue foi resolvida.
