### ISSUE TITLE
Grid com usuários está com problema

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#62]
A grid com usuários está com problema quando a coluna de Titulação está preenchida.
   Para testar, filtre por professores e ordene por titulação. Perceba que a grid é preenchida mas os ultimos registros somem. Ela aparece com X páginas e depois sobe para Y > X páginas. Quando passa pra página seguinte, o registro que deveria ter ido pra essa página não aparece. Assim, tem registros que nunca estão visíveis na grid.

**Comment by jairofsouza** [comment]
Segundo a secretária do curso:
Eu escrevo no perfil do professor e aperto "salvar", logo depois aparece um alerta dizendo que foi salvo, só a página não concerta a quantidade de páginas, então eu reordeno e ele começa a ficar indo e voltando com o nome do último professor e aumentando e diminuindo a quantidade de páginas. No começo ele para rápido, mas de acordo com o que eu vou salvando o de outros professores ele tem mais dificuldade de rearranjar a quantidade de páginas, então atualizo a página (F5) e para com esse negócio das páginas, mas tudo que eu tinha feito com os perfis vai embora.

**Comment by jairofsouza** [comment]
Uma solução que não resolve o problema, mas ameniza, é tirar a coluna Titulação da grid. Realmente ela não é necessária lá. Alias, também não é necessária a coluna id.

**Comment by fanuelson** [comment]
Tudo bem, não consegui identificar o erro no servidor de teste. Mas vou continuar verificando.

**Comment by jairofsouza** [comment]
Para identificar o erro no servidor de teste, faça o seguinte: filtre por professor e edite uns 15 professores colocando como titulação o seguinte texto: "Doutor em Ciência da Computação (UFMG)". Copia  e coloca o mesmo texto na titulação de cada. Isso vai fazer a linha ocupar mais espaço e o erro vai começar a acontecer.

**Comment by fanuelson** [comment]
Issue concertada.

**Comment by fanuelson** [comment]
Jairo, no menu secretária não existe a opção gerenciar usuários, só o administrador possui essa opção no meu projeto.
