### ISSUE TITLE
Problemas com Gerencia de Trabalhos

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#63]
Dando um geral nestes "gerenciar trabalhos" que tá bem estranho:

1 - admin tem a opção de gerenciar trabalhos, contudo, quando clica lá a página não abre. Eu tiraria o Gerenciar Trabalhos do admin
2 - O coordenador tem um gerenciar trabalhos que aparece somente 2 monografias. As duas estão como "Aprovadas", contudo, existem várias monografias aprovadas. Essa página do coordenador é interessante pq pode-se filtrar por tipo (PAA, PI, etc) e ver somente o semestre atual. Até aí tudo bem, com exceção desse problema de não aparecer outras completas (deveria?).
3 - Secretaria tem 2 opções de gerenciar trabalhos, olha que bagunça. Tem o "Gerenciar Trabalhos" e o "Trabalhos e Projetos do Semestre". Esse "Trabalhos e Projetos do Semestre" é na verdade o "Gerenciar Trabalhos" do coordenador! É a mesma página só que com nome diferente no menu. Já o Gerenciar Trabalhos em si, pelo o que estou entendendo, mostra na verdade a lista pública daquele curso mas com opção de editar. Neste caso, o status não faz sentido. Se você reparar também, as duas monografias que estao em Trabalhos e Projetos não estão em Gerenciar Trabalhos. Isso sendo que todas estao como Aprovada. Tem algo muito estranho aí.

Pra resolver essa bagunça toda, o que seria o ideal:
1 - Tirar o gerenciar trabalhos do admin
2 - Entender qual a diferença na consulta dessas páginas Gerenciar Trabalhos e Trabalhos e Projetos do Semestre
3 - Fazer uma mescla dessas duas páginas e deixar só uma chamada Gerenciar Trabalho. Nesta gerenciar trabalho, teria o status como coluna, mas teria as seguintes opções de filtro também:
   3.1. Pesquisar
   3.2. Ano (tendo, dentro do ano, a opção de semestre atual tb)
   3.3. Tipos
   3.4. Semestre Atual

Outra coisa que eu notei:
    quando eu entro no perfil da Alessandreia, aparece 1 monografia sob orientação dela. A de titulo Teste. Lá, aparece a monografia como Não agendada. Se não foi agendada, significa que não foi defendida ainda, certo? Porém, essa mesma monografia aparece Aprovado lá no Gerenciar Trabalhos do coordenador. Uai, o coordenador não pode aprovar uma monografia que nao tem data de defesa. Pode ser que esse status Aprovado esteja errado na tabela? Quando eu clico pra editar o trabalho, ele sai e não deixa editar. Enfim, muita coisa pra analisar aí.

**Comment by jairofsouza** [comment]
Essa issue está relacionado com as issues #49 e #54

**Comment by fanuelson** [comment]
Não Jairo essa questão da alessandreia é um mesmo usuario tem 2 TCCs no banco um tcc dele foi aprovado e o outro ta em andamento que é esse q ta sobre orientação dela.
