### ISSUE TITLE
Lista de anos no filtro da lista pública está com problema

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#66]
Quando abre a tela principal, não aparece a lista de anos. A lista de anos muda quando filtramos por curso. Quando voltamos para "todos os cursos" a lista de anos parece que fica com o valor anterior.

**Comment by jairofsouza** [comment]
O filtro ainda está com problema.
   Quando eu busco por "Lucas" por exemplo, aparece somente 1 monografia. Isso pq o sistema está buscando somente nas monografias mais recentes. Quando eu escolho um curso, aparece os outros Lucas. Quando for usar o filtro, deveria buscar em todos os cursos, caso essa opção esteja selecionado e não somente nas monografias mais recentes.

**Comment by fanuelson** [comment]
Issue resolvida. Agora a opção "Todos" mostra todos os trabalhos já aprovados.

**Comment by jairofsouza** [comment]
"Todos" está mostrando todos os trabalhos aprovados mesmo ou possui um limite? Caso não possua limite, acho que ficou ótimo. É até melhor para ser indexado pelo google. Contudo, tire o texto de "Todos (mais recentes)" e deixe somente "Todos". A gente colocou "mais recentes" só pq não era todos.

**Comment by fanuelson** [comment]
Acho que está mostrando sim Jairo. Eu mesmo criei uma nova função getAllTrabalhosFinalizados(), ela não tem limite não, algumas outras que já estavam no sistema possuem limites.

**Comment by jairofsouza** [comment]
Preciso que vc responda dando certeza disso :-)
