### ISSUE TITLE
Registrar quantidade de views e de downloads de cada monografia

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#67]

**Comment by fanuelson** [comment]
registrar tbm qt de Downloads de arquivos extra Jairo ?

**Comment by jairofsouza** [comment]
Somente PDF do trabalho.

Abs,
Jairo de Souza

**Comment by fanuelson** [comment]
Issue resolvida, atualizei todos os bancos de dados.
