### ISSUE TITLE
Não aparece as monografias sob orientação do professor

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#68]
Eu tenho diversas monografias que eu fui orientador. Mas quando entro na minha página, não aparece nenhuma monografia lá. Não sei se o mesmo se repete na versão de teste ou somente na de produção.

**Comment by fanuelson** [comment]
Mas Jairo, na página de cada professor ou coordenador só aparece as monografias que estão sendo orientadas atualmente(semestre atual), as monografias que já foram orientadas não aparecem.

**Comment by jairofsouza** [comment]
Tem uma opção "mostrar finalizados" lá que eu não tinha visto. Está ok, desculpe.
