### ISSUE TITLE
Alteração na mensagem de login do sistema

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#73]
No login aparece a mensagem "Senha inválida ou usuário não cadastrado". Seria possível verificar esse "ou" para entregar mensagens mais específicas?

**Comment by fanuelson** [comment]
Coloquei essa mensagem "Identificador ou senha inválidos!", não acho que seja bom especificar qual foi o o campo errado Jairo, quer que especifique ?

**Comment by jairofsouza** [comment]
Veja bem: existem as seguintes situações:
* Usuário ou senha inválidos: significa que o usuário não foi autenticado pelo Integra
* Usuário não cadastrado no sistema: significa que o user e senha foi validado pelo integra, mas não consta a matricula dele no sistema de monografias
* Usuário não está ativo no sistema: significa que está cadastrado, mas não está ativo.

Pelo o que eu me lembre, esse ultimo caso está sendo tratado. A mensagem dos dois primeiros casos é que estavam tudo como uma coisa só.
