### ISSUE TITLE
Permitir escolher se usuário pode ser ativo ou não ao importar dados via CSV

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#79]
Opção pode ou não estar no CSV. Seria opcional lá.

**Comment by fanuelson** [comment]
Jairo uma pergunta. Quando estiverem tentando adicionar um usuário que já está no banco de dados eu não adiciono e informo quantos não foram adicionados. Até ai tudo certo.

Mas quando existem 2 ou mais com mesma matrícula no arquivo CSV que é exibido na tela eu adiciono apenas o primeiro e os outros não ou eu não adiciono nenhum que possui matricula igual?

**Comment by jairofsouza** [comment]
Adiciona o primeiro é o outro dará erro. O melhor seria mostrar quais não foi incluído ao invés de só falar q não concluiu tantos. Mas isso pode deixar como melhoria pro futuro (abre nova issue)

Jairo

**Comment by jairofsouza** [comment]
Testei e está ok. Contudo, poderia deixar como "default" os campos marcados como ativos. Será mais comum ativar do que desativar os campos. Ou isso está vindo do CSV?
