### ISSUE TITLE
Erro na exibição dos prazos para o aluno

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#82]
Criei um TCC para o usuário Jorge e não coloquei o PDF. Quando eu entro agora na página do usuário, aparece somente a primeira data (prazo final para envio do projeto). As demais datas não estão aparecendo na tela. No usuário Matheus está aparecendo todas as datas corretamente.

**Comment by fanuelson** [comment]
Jairo, isso não está errado. Sempre foi assim. A lógica é a seguinte:
O único prazo que aparece pra o aluno primeiramente é apenas o prazo para enviar o projeto.
Se ele envia o projeto e o projeto é aprovado ai sim ele começa o trabalho e todos os prazos aparecem para ele.

**Comment by jairofsouza** [comment]
Antes dele começar o projeto, apareciam todos os prazos. Quando o projeto foi criado, apareceu só 1. Não faz sentido aparecer todos só depois do projeto ser aprovado se antes já apareceriam todos. 
    Melhor deixar todos aparecendo sempre. O que muda é a cor ou o negrito dos prazos de acordo com a data atual ou se as tarefas foram entregues ou nao. Mas todos tem q aparecer.

Abs,
Jairo de Souza
