### ISSUE TITLE
Problema ao cadastrar titulação de professores

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#83]
Possivelmente o problema acontece por conta do numero de caracteres no campo de titulação.

**Comment by fanuelson** [comment]
Issue resolvida.
Era exatamente isso Jairo. Aumentei no banco de dados de teste e de produção.

**Comment by jairofsouza** [comment]
Susana testou e está ok, com exceção da titulação do prof Stenio.

Jairo

**Comment by fanuelson** [comment]
Resolvi Jairo, Pode editar o Stenio.

**Comment by fanuelson** [comment]
Jairo resolvi desse jeito que você falou, agora pensando aqui, acho que eu
deveria fazer isso para os outros campos de texto, o que você acha?

2015-08-18 19:18 GMT-03:00 jairofsouza <notifications@github.com>:

> Closed #83 <https://github.com/ufjf-dcc/tcc-web/issues/83>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufjf-dcc/tcc-web/issues/83#event-385893646>.
>



-- 
Fanuel Nunes
Graduando em Sistemas de Informação
Universidade Federal de Juiz de Fora
