### ISSUE TITLE
Ao listar trabalhos na página de coordenador e de secretaria, o filtro Todos não mostra todos os trabalhos

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#84]
Faltam os trabalhos do semestre atual.

**Comment by fanuelson** [comment]
Mas Jairo, está aparecendo os do semestre atual. Eles estão na última página da lista.

**Comment by jairofsouza** [comment]
Ahh, agora entendi. Que tal deixar a ordenação por data ativada então? Assim eles apareceriam na ordem de criação dos trabalhos e fica mais fácil de conferir.

Jairo

**Comment by fanuelson** [comment]
Beleza Jairo, consegui fazer isso. Contudo preciso te perguntar sobre uma lógica do sistema.
Existe 2 campos no banco de dados diferente no TCC, eles são "dataEnvioBanca" e "dataEnvioFinal" .
dataEnvioBanca registra a última vez que o usuário atualizou o projeto ou trabalho.
dataEnvioFinal registra a data em que o trabalho foi finalizado(Aprovado).

La no sistema está confuso pois num lugar ele mostra um em outro lugar ele mostra outro na mesma página.
Você quer que seja exibido qual dos dois na lista de Trabalhos para os coordenadores,admins e secretarias ? E caso algum deles ainda não seja informado, qual mensagem exibir ?

**Comment by jairofsouza** [comment]
Pode ser assim:
   se o trabalho tem envio final, mostrar a dataenviofinal. Caso contrário, mostrar a outra data.

Não pode ter trabalho sem uma dessas datas, não eh? 

Jairo

**Comment by fanuelson** [comment]
trabalho não, mas projeto sim. e dataEnvioFinal os trabalhos ainda não finalizados ainda não tem.

**Comment by fanuelson** [comment]
Isso que vc falou ai acho o certo msm a fazer.
