### ISSUE TITLE
Grids com problema na hora de atualizar

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#9]
As grids com usuários podem ser editadas. Como elas possuem muitos dados, é feito paginação. Ao clicar na edição da grid, o campo editável some pois muda-se a ordenação. Talvez seja mais fácil tirar todas as edições como uma janela ao invés de editar dentro das grids.

**Comment by lucaslarcher** [comment]
Agora a edição é feita em uma janela.

- Foi preciso adicionar a seguinte window no gerenciamento-usuario.zul:

	<window id="editUsuario" title="Editar Usuário"
			visible="false" width="350px" border="normal"
			position="center,center" closable="true"
			onClose="self.setVisible(false); event.stopPropagation();">
			<grid>
				<columns>
					<column width="125px" />
					<column />
				</columns>
				<rows>
					<row>
						<label value="Tipo:" />
						<combobox id="cmbTipoUsuario" width="100%"
							readonly="true" model="@load(vm.tiposUsuario)"
							selectedItem="@bind(vm.editUsuario.tipoUsuario)"
							value="@load(vm.editUsuario.tipoUsuario.nomeTipoUsuario)"
							disabled="true" 
							onChange="@command('typeChange', titu=txtTitu, comboc=comboCurso, combod=comboDepartamento)">
							<template name="model">
								<comboitem
									label="@load(each.nomeTipoUsuario)" />
							</template>
						</combobox>
					</row>

					<row>
						<label
							value="Identificador" />
						<textbox
							value="@bind(vm.editUsuario.matricula)"
							tabindex="1" width="100%" readonly="true"/>
					</row>

					<row>
						<label value="Nome do Usuário:" />
						<textbox
							value="@bind(vm.editUsuario.nomeUsuario)"
							tabindex="1" width="100%"/>
					</row>

					<row>
						<label value="Email:" />
						<textbox
							value="@bind(vm.editUsuario.email)"
							tabindex="1" width="100%"/>
					</row>

					<row>
						<label value="Titulação:" />
						<textbox id="txtTitu"
							readonly="true"
							disabled="false"
							value="@bind(vm.editUsuario.titulacao)"
							tabindex="1" width="100%" />
					</row>

					<row>
						<label value="Curso:" />
						<combobox id="comboCurso" width="100%"
							readonly="true" model="@load(vm.cursos)"
							
							selectedItem="@bind(vm.editUsuario.curso)"
							disabled="true">
							<template name="model">
								<comboitem
									label="@load(each.nomeCurso)" />
							</template>
						</combobox>
					</row>

					<row>
						<label value="Departamento:" />
						<combobox id="comboDepartamento" width="100%"
							readonly="true" model="@load(vm.departamentos)"
							
							selectedItem="@bind(vm.editUsuario.departamento)"
							disabled="true">
							<template name="model">
								<comboitem
									label="@load(each.nomeDepartamento)" />
							</template>
						</combobox>
					</row>
				</rows>
			</grid>
			<div align="center">
				<button label="Salvar"
					onClick="@command('editUser', window=editUsuario)" width="75px"
					style="margin-top:5px" />
			</div>
		</window>

- Foram adicionadas as seguintes funçoes no GerenciamentoUsuarioController.java:

/* Edita propriedades de um usuário */
	@Command
	public void editUsuario(@BindingParam("window") Window window, @BindingParam("usuario") Usuario user) {
		editUsuario = user;
		((Combobox)window.getChildren().get(0).getChildren().get(1).getChildren().get(0).getChildren().get(1)).setValue(editUsuario.getTipoUsuario().getNomeTipoUsuario());
		((Textbox)window.getChildren().get(0).getChildren().get(1).getChildren().get(1).getChildren().get(1)).setValue(editUsuario.getMatricula());
		((Textbox)window.getChildren().get(0).getChildren().get(1).getChildren().get(2).getChildren().get(1)).setValue(editUsuario.getNomeUsuario());
		((Textbox)window.getChildren().get(0).getChildren().get(1).getChildren().get(3).getChildren().get(1)).setValue(editUsuario.getEmail());
		((Textbox)window.getChildren().get(0).getChildren().get(1).getChildren().get(4).getChildren().get(1)).setValue(editUsuario.getTitulacao());
		if(editUsuario.getCurso()!=null)
			((Combobox)window.getChildren().get(0).getChildren().get(1).getChildren().get(5).getChildren().get(1)).setValue(editUsuario.getCurso().getNomeCurso());
		else
			((Combobox)window.getChildren().get(0).getChildren().get(1).getChildren().get(5).getChildren().get(1)).setValue("Nenhum");
		if(editUsuario.getDepartamento()!=null)
			((Combobox)window.getChildren().get(0).getChildren().get(1).getChildren().get(6).getChildren().get(1)).setValue(editUsuario.getDepartamento().getNomeDepartamento());
		else
			((Combobox)window.getChildren().get(0).getChildren().get(1).getChildren().get(6).getChildren().get(1)).setValue("Nenhum");
	
		
		Usuario usuario = (Usuario) SessionManager.getAttribute("usuario");
		if(usuario.getTipoUsuario().getIdTipoUsuario() == Usuario.ADMINISTRADOR)
		{
			((Combobox)window.getChildren().get(0).getChildren().get(1).getChildren().get(0).getChildren().get(1)).setDisabled(false);
			((Textbox)window.getChildren().get(0).getChildren().get(1).getChildren().get(1).getChildren().get(1)).setReadonly(false);
			((Textbox)window.getChildren().get(0).getChildren().get(1).getChildren().get(4).getChildren().get(1)).setReadonly(false);
			((Combobox)window.getChildren().get(0).getChildren().get(1).getChildren().get(5).getChildren().get(1)).setDisabled(false);
			((Combobox)window.getChildren().get(0).getChildren().get(1).getChildren().get(6).getChildren().get(1)).setDisabled(false);
		}
		
		window.doModal();
		window.setVisible(true);
	}
	
	@Command
	public void editUser(@BindingParam("window") final Window window)
	{
		
		if(usuarioBusiness.validate(editUsuario, editUsuario.getMatricula(), true))
		{
			usuarioBusiness.editar(editUsuario);
			Clients.clearBusy(window);
			Messagebox.show(
					"Usuário salvo!",
					"Sucesso", Messagebox.OK,
					Messagebox.INFORMATION);
			window.setVisible(false);
		}	
		else
		{
			Messagebox.show(
					"Erro ao salvar as mudanças do usuário",
					"Erro", Messagebox.OK,
					Messagebox.INFORMATION);
		}
	}
