### ISSUE TITLE
Verificar se um aluno pode ter 2 monografias associadas a ele [para teste]

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#91]
Pense no seguinte caso: um aluno foi do curso de ciencias exatas, defendeu monografia, e agora está na computacao e está defendendo nova monografia. Ele teria, em períodos distintos, usado o sistema em 2 processos de orientacao distintos. O sistema permite isso? Favor testar.

**Comment by fanuelson** [comment]
Permite sim Jairo, em períodos distintos sim. Basta ativar o aluno novamente e ele pode inciar outro trabalho.
