### ISSUE TITLE
Geração de PDF de divulgação das bancas

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#95]
Criar uma opção para coordenadores e secretários para gerar um PDF de divulgação das bancas marcadas. Exibir as bancas marcadas e a possibilidade de selecionar quais trabalhos estarão no PDF. O  modelo pode ser parecido com o enviado atualmente (me pedir)

**Comment by jairofsouza** [comment]
1) O botão gerar PDF se esconde na tela se a janela estiver menor. Parece que tá fixo numa posição que, dependendo do tamanho da janela ou da resolução, ela não aparece e não tem como rolar. Ela deveria se mover igual acontece com a grid na mesma janela.

2) Na geração do PDF, aparece uns "null" lá. O que é isso? É a titulação que está faltando? Se estiver faltando, deixa vazio, mas não null.

3) CoOrientador se escreve "Coorientador" (tira o O maiúsculo).

4) Está aparecendo "16h  h" (com 2 h)

5) Para que aquela linha da sala, data, etc, não ficar desalinhada (repara como não está tudo seguindo a mesma linha...), pq vc não cria a linha inteira por código ao invés de preencher o PDF os pedacinhos?

6) Está aparecendo o Alex como coorientador e como membro da banca. O sistema está deixando incluir o mesmo professor como os dois?! Em caso positivo, acabamos de encontrar um erro no sistema então.

7) Por curiosidade: o nome do curso no título da página se modifica dependendo do curso do aluno? Sim, né?

8) No título "Composição da Banca do Trabalho de Conclusão do curso", coloca o "C" de curso tb em maiúsculo.

9) Quais os trabalhos que aparecem na seleção para gerar o PDF? Está aparecendo um "Aprovado", mas deveria aparecer todos os que ainda não tiveram ainda defendido. Ou seja, aqueles que estão em "TAA". Se foi aprovado, quer dizer que o trabalho já foi defendido, então não precisa mais divulgar a banca aos alunos.

**Comment by fanuelson** [comment]
Jairo, em relação ao item 5, eu estou tentando preencher somente com dados os campos porque assim é fácil de criar outros. Por código fica menos dinâmico, mais complicado de criar outros documentos. Se deixar assim é fácil de outros cursos terem seus próprios documentos e nem precisaria implementar nada. O que você acha ?

Em relação ao 9. Sim. pode-se marcar quantos quiser e vai ser gerado um PDF onde cada página é a divulgação de cada banca.

Vou fazer essas modificações e te aviso.

**Comment by fanuelson** [comment]
O Item 6 Jairo, você me disse uma vez que tem que colocar o orientador como banca também. É pra retirar ? Retiro da Ata também ?

**Comment by jairofsouza** [comment]
O orientador e coorientador faz parte da banca. Assim, ele recebe formulário de avaliacao tb e o nome aparece. Contudo, veja que apareceu o Alex 2x no documento. Ele aparece 1x no documento, igual o orientador.
