### ISSUE TITLE
Google Scholar ainda não indexa o repositório

### ISSUE THREAD

**Issue by jairofsouza** [ufjf-dcc/tcc-web#98]
O GS ainda não está indexando o repositório e a inserção das metatags não foi o suficiente. Descobri uma página para incluir o repositório na indexação como um site confiável [1], contudo, teremos que fazer algumas modificações.

1 - Precisamos ter uma URL que mostre todos os trabalhos de um certo ano. Na página inicial pode-se escolher um ano e filtrar aqueles trabalhos. Contudo, isso não gera uma URL nova. Teremos que ter algo como http://www.monografias.ice.ufjf.br/tcc-web/list?year=2015 que abre a mesma página principal mas já filtra por trabalhos desse ano especificado.

2 - É necessário ter uma página que lista todos os anos disponíveis. Poderia ser algo como http://www.monografias.ice.ufjf.br/tcc-web/by-year. Nessa página, abriria uma tabela com os anos disponíveis e um link para cada ano (link acima).

3 = Na página principal, terá que ter um link para essa lista de anos. Minha sugestão é criar um botão depois de "Buscar" chamado de "Visualizar lista anual". Eu colocaria o Pesquisar mais perto do Curso, arrastando tudo para a esquerda e deixando esse visualizar por ano lá na direita.

PS: Peço que não submeta o formulário [1]. Deixa que eu preencho e envio pra eles depois que estiver tudo certo.

[1] https://partnerdash.google.com/partnerdash/d/scholarinclusions#p:id=new

**Comment by jairofsouza** [comment]
Ah, essas páginas by-year e list devem ser geradas em JSP e não ZK, ok? Pois precisam ser indexadas.

**Comment by fanuelson** [comment]
Jairo se eu passar por GET o ano ao pesquisar e ele ir na url como http://www.monografias.ice.ufjf.br/tcc-web/list?year=2015 já resolveria o problema ?

**Comment by jairofsouza** [comment]
Resolve o item 1 somente.

**Comment by fanuelson** [comment]
Veja no sistema de teste se é aquilo o esperado Jairo.

**Comment by fanuelson** [comment]
Jaaaairo,

Consegui preencher o pdf atravez do campo de texto.

2015-10-01 17:53 GMT-03:00 jairofsouza <notifications@github.com>:

> Resolve o item 1 somente.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufjf-dcc/tcc-web/issues/98#issuecomment-144844905>.
>



-- 
Fanuel Nunes
Graduando em Sistemas de Informação
Universidade Federal de Juiz de Fora

**Comment by fanuelson** [comment]
Jairo,

Tem como a gente se reunir amanha ?

Abs.

Em 1 de outubro de 2015 20:37, Fanuel Francisco <fanuelson@gmail.com>
escreveu:

> Jaaaairo,
>
> Consegui preencher o pdf atravez do campo de texto.
>
> 2015-10-01 17:53 GMT-03:00 jairofsouza <notifications@github.com>:
>
>> Resolve o item 1 somente.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ufjf-dcc/tcc-web/issues/98#issuecomment-144844905>.
>>
>
>
>
> --
> Fanuel Nunes
> Graduando em Sistemas de Informação
> Universidade Federal de Juiz de Fora
>



-- 
Fanuel Nunes
Graduando em Sistemas de Informação
Universidade Federal de Juiz de Fora
